// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6j6NwKn0iHTSAhUoTCPf1Amn2GqT3G1I',
    appId: '1:624547760238:web:84121397246fa5b93f7e7f',
    messagingSenderId: '624547760238',
    projectId: 'agenda-contatos-ca083',
    authDomain: 'agenda-contatos-ca083.firebaseapp.com',
    storageBucket: 'agenda-contatos-ca083.firebasestorage.app',
    measurementId: 'G-CCJ5Y3478Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA28ZWffZe5Gb8-KVoqoGJ2hmXjQBkSyek',
    appId: '1:624547760238:android:f3e97872cba760d03f7e7f',
    messagingSenderId: '624547760238',
    projectId: 'agenda-contatos-ca083',
    storageBucket: 'agenda-contatos-ca083.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ19PPbHFE2VVYajDWcPTiiKpzIy2ES7E',
    appId: '1:624547760238:ios:5eb049fd78521e443f7e7f',
    messagingSenderId: '624547760238',
    projectId: 'agenda-contatos-ca083',
    storageBucket: 'agenda-contatos-ca083.firebasestorage.app',
    iosBundleId: 'com.example.agendaContatos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ19PPbHFE2VVYajDWcPTiiKpzIy2ES7E',
    appId: '1:624547760238:ios:5eb049fd78521e443f7e7f',
    messagingSenderId: '624547760238',
    projectId: 'agenda-contatos-ca083',
    storageBucket: 'agenda-contatos-ca083.firebasestorage.app',
    iosBundleId: 'com.example.agendaContatos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6j6NwKn0iHTSAhUoTCPf1Amn2GqT3G1I',
    appId: '1:624547760238:web:4af82c9b16c6563d3f7e7f',
    messagingSenderId: '624547760238',
    projectId: 'agenda-contatos-ca083',
    authDomain: 'agenda-contatos-ca083.firebaseapp.com',
    storageBucket: 'agenda-contatos-ca083.firebasestorage.app',
    measurementId: 'G-EMVJWSYEBQ',
  );
}
